### ISSUE TITLE
Error with installing smart contract on UBuntu 16.04

### ISSUE THREAD

**Issue by SharedMocha** [nos/nos-local#7]
Running below command gives error in neo-python on Ubuntu 16.04
neo> import contract /smart-contracts/contract.avm 0710 05 True False

```
Please fill out the following contract details:
[Contract Name] > 1
[Contract Version] > 1
[Contract Author] > 1
[Contract Email] > 1
[Contract Description] > 1
Creating smart contract....
                 Name: 1 
              Version: 1
               Author: 1 
                Email: 1 
          Description: 1 
        Needs Storage: True 
 Needs Dynamic Invoke: False 
{
    "hash": "0xe60a3fa8149a853eb4dff4f6ed93c931646a9e22",
    "script": "0123c56b6a00527ac46a51527ac46a51c300c36a52527ac46a51c351c36a53527ac46a53c3062e6f776e65727e6a54527ac46a53c3072e7461726765747e6a55527ac41423ba2703c53263e8d6e522dc32203339dcd8eee96a56527ac46a00c309476574446f6d61696e9c64350068164e656f2e53746f726167652e476574436f6e74657874616a55c37c680f4e656f2e53746f726167652e476574616c7566616a52c368184e656f2e52756e74696d652e436865636b5769746e657373616a57527ac46a57c36328000e4e6f7420417574686f72697a6564680f4e656f2e52756e74696d652e4c6f6761006c7566610a417574686f72697a6564680f4e656f2e52756e74696d652e4c6f67616a00c30e5265676973746572446f6d61696e9c64ac006a56c368184e656f2e52756e74696d652e436865636b5769746e65737361648b006a51c352c36a58527ac468164e656f2e53746f726167652e476574436f6e74657874616a54c36a58c35272680f4e656f2e53746f726167652e507574616a51c3c0549c6440006a51c353c36a59527ac468164e656f2e53746f726167652e476574436f6e74657874616a55c36a59c35272680f4e656f2e53746f726167652e5075746161516c7566616a00c30f536574446f6d61696e5461726765749c6487006a54c368184e656f2e52756e74696d652e436865636b5769746e657373616324006a56c368184e656f2e52756e74696d652e436865636b5769746e65737361644500616a51c352c36a59527ac468164e656f2e53746f726167652e476574436f6e74657874616a55c36a59c35272680f4e656f2e53746f726167652e50757461516c7566616a00c30c44656c657465446f6d61696e9c648c006a56c368184e656f2e52756e74696d652e436865636b5769746e65737361646b0068164e656f2e53746f726167652e476574436f6e74657874616a54c37c68124e656f2e53746f726167652e44656c6574656168164e656f2e53746f726167652e476574436f6e74657874616a55c37c68124e656f2e53746f726167652e44656c65746561516c756661006c75665ec56b6a00527ac46a51527ac46a51c36a00c3946a52527ac46a52c3c56a53527ac4006a54527ac46a00c36a55527ac461616a00c36a51c39f6433006a54c36a55c3936a56527ac46a56c36a53c36a54c37bc46a54c351936a54527ac46a55c36a54c3936a00527ac462c8ff6161616a53c36c7566",
    "parameters": "0710",
    "returntype": "05"
}
Could not execute command: invalid literal for int() with base 10: b'\x05'
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/usr/local/lib/python3.6/dist-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/neo-python/neo/bin/prompt.py", line 1030, in run
    traceback.print_stack()
Traceback (most recent call last):
  File "/neo-python/neo/bin/prompt.py", line 978, in run
    self.do_import(arguments)
  File "/neo-python/neo/bin/prompt.py", line 378, in do_import
    return self.load_smart_contract(arguments)
  File "/neo-python/neo/bin/prompt.py", line 803, in load_smart_contract
    contract_script = GatherContractDetails(function_code, self)
  File "/neo-python/neo/Prompt/Commands/LoadSmartContract.py", line 185, in GatherContractDetails
    function_code.ContractProperties, function_code.ReturnTypeBigInteger,
  File "/neo-python/neo/Core/FunctionCode.py", line 19, in ReturnTypeBigInteger
    return BigInteger(self.ReturnType)
ValueError: invalid literal for int() with base 10: b'\x05'
neo> 
neo> import contract /smart-contracts/contract.avm 0710 05 True False
Please fill out the following contract details:
[Contract Name] > 1
[Contract Version] > 1
[Contract Author] > 1
[Contract Email] > 1
[Contract Description] > 11
Creating smart contract....
                 Name: 1 
              Version: 1
               Author: 1 
                Email: 1 
          Description: 11 
        Needs Storage: True 
 Needs Dynamic Invoke: False 
{
    "hash": "0xe60a3fa8149a853eb4dff4f6ed93c931646a9e22",
    "script": "0123c56b6a00527ac46a51527ac46a51c300c36a52527ac46a51c351c36a53527ac46a53c3062e6f776e65727e6a54527ac46a53c3072e7461726765747e6a55527ac41423ba2703c53263e8d6e522dc32203339dcd8eee96a56527ac46a00c309476574446f6d61696e9c64350068164e656f2e53746f726167652e476574436f6e74657874616a55c37c680f4e656f2e53746f726167652e476574616c7566616a52c368184e656f2e52756e74696d652e436865636b5769746e657373616a57527ac46a57c36328000e4e6f7420417574686f72697a6564680f4e656f2e52756e74696d652e4c6f6761006c7566610a417574686f72697a6564680f4e656f2e52756e74696d652e4c6f67616a00c30e5265676973746572446f6d61696e9c64ac006a56c368184e656f2e52756e74696d652e436865636b5769746e65737361648b006a51c352c36a58527ac468164e656f2e53746f726167652e476574436f6e74657874616a54c36a58c35272680f4e656f2e53746f726167652e507574616a51c3c0549c6440006a51c353c36a59527ac468164e656f2e53746f726167652e476574436f6e74657874616a55c36a59c35272680f4e656f2e53746f726167652e5075746161516c7566616a00c30f536574446f6d61696e5461726765749c6487006a54c368184e656f2e52756e74696d652e436865636b5769746e657373616324006a56c368184e656f2e52756e74696d652e436865636b5769746e65737361644500616a51c352c36a59527ac468164e656f2e53746f726167652e476574436f6e74657874616a55c36a59c35272680f4e656f2e53746f726167652e50757461516c7566616a00c30c44656c657465446f6d61696e9c648c006a56c368184e656f2e52756e74696d652e436865636b5769746e65737361646b0068164e656f2e53746f726167652e476574436f6e74657874616a54c37c68124e656f2e53746f726167652e44656c6574656168164e656f2e53746f726167652e476574436f6e74657874616a55c37c68124e656f2e53746f726167652e44656c65746561516c756661006c75665ec56b6a00527ac46a51527ac46a51c36a00c3946a52527ac46a52c3c56a53527ac4006a54527ac46a00c36a55527ac461616a00c36a51c39f6433006a54c36a55c3936a56527ac46a56c36a53c36a54c37bc46a54c351936a54527ac46a55c36a54c3936a00527ac462c8ff6161616a53c36c7566",
    "parameters": "0710",
    "returntype": "05"
}
Could not execute command: invalid literal for int() with base 10: b'\x05'
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/usr/local/lib/python3.6/dist-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/neo-python/neo/bin/prompt.py", line 1030, in run
    traceback.print_stack()
Traceback (most recent call last):
  File "/neo-python/neo/bin/prompt.py", line 978, in run
    self.do_import(arguments)
  File "/neo-python/neo/bin/prompt.py", line 378, in do_import
    return self.load_smart_contract(arguments)
  File "/neo-python/neo/bin/prompt.py", line 803, in load_smart_contract
    contract_script = GatherContractDetails(function_code, self)
  File "/neo-python/neo/Prompt/Commands/LoadSmartContract.py", line 185, in GatherContractDetails
    function_code.ContractProperties, function_code.ReturnTypeBigInteger,
  File "/neo-python/neo/Core/FunctionCode.py", line 19, in ReturnTypeBigInteger
    return BigInteger(self.ReturnType)
ValueError: invalid literal for int() with base 10: b'\x05'
```

**Comment by DalderupMaurice** [comment]
Have you been able to resolve the issue or does it still persist? @SharedMocha

**Comment by DalderupMaurice** [comment]
Closing as there's no response.
Feel free te reopen!
